// <auto-generated />
using System;
using MiTutor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MiTutor.Migrations
{
    [DbContext(typeof(MiTutorContext))]
    [Migration("20190915210740_SecondUpdate")]
    partial class SecondUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MiTutor.Models.Availability", b =>
                {
                    b.Property<int>("AvailabilityId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("TutorId");

                    b.HasKey("AvailabilityId");

                    b.HasIndex("TutorId")
                        .IsUnique();

                    b.ToTable("Availability");
                });

            modelBuilder.Entity("MiTutor.Models.AvailabilityDay", b =>
                {
                    b.Property<int>("AvailabilityDayId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AvailabilityId");

                    b.Property<string>("Day");

                    b.Property<DateTime>("EndTime");

                    b.Property<DateTime>("StartTime");

                    b.HasKey("AvailabilityDayId");

                    b.HasIndex("AvailabilityId");

                    b.ToTable("AvailabilityDay");
                });

            modelBuilder.Entity("MiTutor.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LastName");

                    b.Property<string>("Name");

                    b.Property<int>("Semester");

                    b.Property<int>("UniversityId");

                    b.HasKey("PersonId");

                    b.HasIndex("UniversityId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("MiTutor.Models.Qualification", b =>
                {
                    b.Property<int>("QualificationId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AdresseeId");

                    b.Property<int>("AdresserId");

                    b.Property<int>("AdresserRole");

                    b.Property<string>("Comment");

                    b.Property<int>("Rate");

                    b.Property<int>("TutoringSessionId");

                    b.HasKey("QualificationId");

                    b.HasIndex("AdresseeId");

                    b.HasIndex("AdresserId");

                    b.HasIndex("TutoringSessionId");

                    b.ToTable("Qualification");
                });

            modelBuilder.Entity("MiTutor.Models.Student", b =>
                {
                    b.Property<int>("StudentId");

                    b.Property<int>("Points");

                    b.Property<int?>("TutoringSessionTutoringId");

                    b.HasKey("StudentId");

                    b.HasIndex("TutoringSessionTutoringId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("MiTutor.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("StudentId");

                    b.Property<int?>("TutorId");

                    b.HasKey("SubjectId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TutorId");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("MiTutor.Models.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("SubjectId");

                    b.Property<int?>("TutoringOfferTutoringId");

                    b.HasKey("TopicId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TutoringOfferTutoringId");

                    b.ToTable("Topic");
                });

            modelBuilder.Entity("MiTutor.Models.Tutor", b =>
                {
                    b.Property<int>("TutorId");

                    b.Property<string>("Description");

                    b.Property<int>("Points");

                    b.HasKey("TutorId");

                    b.ToTable("Tutor");
                });

            modelBuilder.Entity("MiTutor.Models.TutoringOffer", b =>
                {
                    b.Property<int>("TutoringId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Capacity");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Place");

                    b.Property<int?>("SubjectId");

                    b.Property<int>("TutorId");

                    b.HasKey("TutoringId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TutorId");

                    b.ToTable("TutoringOffer");

                    b.HasDiscriminator<string>("Discriminator").HasValue("TutoringOffer");
                });

            modelBuilder.Entity("MiTutor.Models.University", b =>
                {
                    b.Property<int>("UniversityId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("UniversityId");

                    b.ToTable("University");
                });

            modelBuilder.Entity("MiTutor.Models.User", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("MiTutor.Models.TutoringSession", b =>
                {
                    b.HasBaseType("MiTutor.Models.TutoringOffer");

                    b.Property<int?>("TutorId1");

                    b.HasIndex("TutorId1");

                    b.ToTable("TutoringSession");

                    b.HasDiscriminator().HasValue("TutoringSession");
                });

            modelBuilder.Entity("MiTutor.Models.Availability", b =>
                {
                    b.HasOne("MiTutor.Models.Tutor", "Tutor")
                        .WithOne("Availability")
                        .HasForeignKey("MiTutor.Models.Availability", "TutorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MiTutor.Models.AvailabilityDay", b =>
                {
                    b.HasOne("MiTutor.Models.Availability", "Availability")
                        .WithMany("AvailabilityDays")
                        .HasForeignKey("AvailabilityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MiTutor.Models.Person", b =>
                {
                    b.HasOne("MiTutor.Models.University", "University")
                        .WithMany("Persons")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MiTutor.Models.Qualification", b =>
                {
                    b.HasOne("MiTutor.Models.Person", "Adressee")
                        .WithMany("QualificationsGiven")
                        .HasForeignKey("AdresseeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MiTutor.Models.Person", "Adresser")
                        .WithMany("QualificationsReceived")
                        .HasForeignKey("AdresserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MiTutor.Models.TutoringSession", "TutoringSession")
                        .WithMany("Qualifications")
                        .HasForeignKey("TutoringSessionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MiTutor.Models.Student", b =>
                {
                    b.HasOne("MiTutor.Models.Person", "Person")
                        .WithOne("Student")
                        .HasForeignKey("MiTutor.Models.Student", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MiTutor.Models.TutoringSession")
                        .WithMany("Students")
                        .HasForeignKey("TutoringSessionTutoringId");
                });

            modelBuilder.Entity("MiTutor.Models.Subject", b =>
                {
                    b.HasOne("MiTutor.Models.Student")
                        .WithMany("Subjects")
                        .HasForeignKey("StudentId");

                    b.HasOne("MiTutor.Models.Tutor")
                        .WithMany("Subjects")
                        .HasForeignKey("TutorId");
                });

            modelBuilder.Entity("MiTutor.Models.Topic", b =>
                {
                    b.HasOne("MiTutor.Models.Subject", "Subject")
                        .WithMany("Topics")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MiTutor.Models.TutoringOffer")
                        .WithMany("Topics")
                        .HasForeignKey("TutoringOfferTutoringId");
                });

            modelBuilder.Entity("MiTutor.Models.Tutor", b =>
                {
                    b.HasOne("MiTutor.Models.Person", "Person")
                        .WithOne("Tutor")
                        .HasForeignKey("MiTutor.Models.Tutor", "TutorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MiTutor.Models.TutoringOffer", b =>
                {
                    b.HasOne("MiTutor.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId");

                    b.HasOne("MiTutor.Models.Tutor", "Tutor")
                        .WithMany("TutoringOffers")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MiTutor.Models.User", b =>
                {
                    b.HasOne("MiTutor.Models.Person", "Person")
                        .WithOne("User")
                        .HasForeignKey("MiTutor.Models.User", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MiTutor.Models.TutoringSession", b =>
                {
                    b.HasOne("MiTutor.Models.Tutor")
                        .WithMany("TutoringSessions")
                        .HasForeignKey("TutorId1");
                });
#pragma warning restore 612, 618
        }
    }
}
